namespace RLottie
{
    [default_interface]
    runtimeclass LottieAnimation : Windows.Foundation.IClosable
    {
        //static Microsoft.Graphics.Canvas.CanvasBitmap CreateBitmap(Microsoft.Graphics.Canvas.ICanvasResourceCreator resourceCreator, Int32 width, Int32 height);

        static LottieAnimation LoadFromFile(String filePath, Boolean precache, Windows.Foundation.Collections.IMapView<UInt32, UInt32> colorReplacement);
        static LottieAnimation LoadFromData(String jsonData, String cacheKey, Boolean precache, Windows.Foundation.Collections.IMapView<UInt32, UInt32> colorReplacement);

        void CreateCache(Int32 width, Int32 height);

        [default_overload]
        void RenderSync(Microsoft.Graphics.Canvas.CanvasBitmap bitmap, Int32 frame);
        void RenderSync(Windows.UI.Xaml.Media.Imaging.WriteableBitmap bitmap, Int32 frame);

        Double FrameRate { get; };
        Int32 TotalFrame { get; };
        Windows.Foundation.Size Size { get; };
        Boolean ShouldCache { get; };
    }
}
